export type RootStackParamList = {
    Intro: undefined;
    Login: undefined;
    SignUp: undefined;
    Registration: undefined;
    Dash: undefined;
    MyHealth: undefined;
    Report: undefined;
    Doctor: undefined;
    Order: undefined;
    Schedule: undefined;
    LogOut: undefined;
    Doca: undefined;
    Nurse:undefined;
    Profile:undefined;
    BirthReport:undefined;
    DownlordBirthC:undefined;
    ClinicReport:undefined;
    DownlordCilnic:undefined;
  };